name: Test Environment

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt
        
    - name: Test environment
      run: |
        python test_github_actions.py
        
    - name: Show test results
      run: |
        if [ -f "results/test_result.txt" ]; then
          echo "测试结果:"
          cat results/test_result.txt
        else
          echo "测试结果文件不存在"
        fi
        
    - name: List files
      run: |
        echo "当前目录内容:"
        ls -la
        echo ""
        echo "src目录内容:"
        if [ -d "src" ]; then
          ls -la src/
        else
          echo "src目录不存在"
        fi
